# Generated by Django 3.2.8 on 2023-01-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_auto_20230110_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='user',
            new_name='users',
        ),
    ]
