# Generated by Django 3.2.8 on 2023-01-10 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_film_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='users',
            field=models.ManyToManyField(related_name='films', through='films.UserFilms', to=settings.AUTH_USER_MODEL),
        ),
    ]
