# Generated by Django 3.2.8 on 2023-01-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
